package model;
// Generated 15 ene 2025, 9:52:52 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

/**
 * UserId generated by hbm2java
 */
public class UserId implements java.io.Serializable {

	private String alterPriv;
	private String alterRoutinePriv;
	private String authenticationString;
	private String createPriv;
	private String createRoutinePriv;
	private String createTablespacePriv;
	private String createTmpTablePriv;
	private String createUserPriv;
	private String createViewPriv;
	private String defaultRole;
	private String deleteHistoryPriv;
	private String deletePriv;
	private String dropPriv;
	private String eventPriv;
	private String executePriv;
	private String filePriv;
	private String grantPriv;
	private String host;
	private String indexPriv;
	private String insertPriv;
	private String isRole;
	private String lockTablesPriv;
	private long maxConnections;
	private long maxQuestions;
	private BigDecimal maxStatementTime;
	private long maxUpdates;
	private long maxUserConnections;
	private String password;
	private String passwordExpired;
	private String plugin;
	private String processPriv;
	private String referencesPriv;
	private String reloadPriv;
	private String replClientPriv;
	private String replSlavePriv;
	private String selectPriv;
	private String showDbPriv;
	private String showViewPriv;
	private String shutdownPriv;
	private String sslCipher;
	private String sslType;
	private String superPriv;
	private String triggerPriv;
	private String updatePriv;
	private String user;
	private String x509Issuer;
	private String x509Subject;

	public UserId() {
	}

	public UserId(String authenticationString, String defaultRole, String host, long maxConnections, long maxQuestions,
			BigDecimal maxStatementTime, long maxUpdates, long maxUserConnections, String passwordExpired,
			String plugin, String sslCipher, String user, String x509Issuer, String x509Subject) {
		this.authenticationString = authenticationString;
		this.defaultRole = defaultRole;
		this.host = host;
		this.maxConnections = maxConnections;
		this.maxQuestions = maxQuestions;
		this.maxStatementTime = maxStatementTime;
		this.maxUpdates = maxUpdates;
		this.maxUserConnections = maxUserConnections;
		this.passwordExpired = passwordExpired;
		this.plugin = plugin;
		this.sslCipher = sslCipher;
		this.user = user;
		this.x509Issuer = x509Issuer;
		this.x509Subject = x509Subject;
	}

	public UserId(String alterPriv, String alterRoutinePriv, String authenticationString, String createPriv,
			String createRoutinePriv, String createTablespacePriv, String createTmpTablePriv, String createUserPriv,
			String createViewPriv, String defaultRole, String deleteHistoryPriv, String deletePriv, String dropPriv,
			String eventPriv, String executePriv, String filePriv, String grantPriv, String host, String indexPriv,
			String insertPriv, String isRole, String lockTablesPriv, long maxConnections, long maxQuestions,
			BigDecimal maxStatementTime, long maxUpdates, long maxUserConnections, String password,
			String passwordExpired, String plugin, String processPriv, String referencesPriv, String reloadPriv,
			String replClientPriv, String replSlavePriv, String selectPriv, String showDbPriv, String showViewPriv,
			String shutdownPriv, String sslCipher, String sslType, String superPriv, String triggerPriv,
			String updatePriv, String user, String x509Issuer, String x509Subject) {
		this.alterPriv = alterPriv;
		this.alterRoutinePriv = alterRoutinePriv;
		this.authenticationString = authenticationString;
		this.createPriv = createPriv;
		this.createRoutinePriv = createRoutinePriv;
		this.createTablespacePriv = createTablespacePriv;
		this.createTmpTablePriv = createTmpTablePriv;
		this.createUserPriv = createUserPriv;
		this.createViewPriv = createViewPriv;
		this.defaultRole = defaultRole;
		this.deleteHistoryPriv = deleteHistoryPriv;
		this.deletePriv = deletePriv;
		this.dropPriv = dropPriv;
		this.eventPriv = eventPriv;
		this.executePriv = executePriv;
		this.filePriv = filePriv;
		this.grantPriv = grantPriv;
		this.host = host;
		this.indexPriv = indexPriv;
		this.insertPriv = insertPriv;
		this.isRole = isRole;
		this.lockTablesPriv = lockTablesPriv;
		this.maxConnections = maxConnections;
		this.maxQuestions = maxQuestions;
		this.maxStatementTime = maxStatementTime;
		this.maxUpdates = maxUpdates;
		this.maxUserConnections = maxUserConnections;
		this.password = password;
		this.passwordExpired = passwordExpired;
		this.plugin = plugin;
		this.processPriv = processPriv;
		this.referencesPriv = referencesPriv;
		this.reloadPriv = reloadPriv;
		this.replClientPriv = replClientPriv;
		this.replSlavePriv = replSlavePriv;
		this.selectPriv = selectPriv;
		this.showDbPriv = showDbPriv;
		this.showViewPriv = showViewPriv;
		this.shutdownPriv = shutdownPriv;
		this.sslCipher = sslCipher;
		this.sslType = sslType;
		this.superPriv = superPriv;
		this.triggerPriv = triggerPriv;
		this.updatePriv = updatePriv;
		this.user = user;
		this.x509Issuer = x509Issuer;
		this.x509Subject = x509Subject;
	}

	public String getAlterPriv() {
		return this.alterPriv;
	}

	public void setAlterPriv(String alterPriv) {
		this.alterPriv = alterPriv;
	}

	public String getAlterRoutinePriv() {
		return this.alterRoutinePriv;
	}

	public void setAlterRoutinePriv(String alterRoutinePriv) {
		this.alterRoutinePriv = alterRoutinePriv;
	}

	public String getAuthenticationString() {
		return this.authenticationString;
	}

	public void setAuthenticationString(String authenticationString) {
		this.authenticationString = authenticationString;
	}

	public String getCreatePriv() {
		return this.createPriv;
	}

	public void setCreatePriv(String createPriv) {
		this.createPriv = createPriv;
	}

	public String getCreateRoutinePriv() {
		return this.createRoutinePriv;
	}

	public void setCreateRoutinePriv(String createRoutinePriv) {
		this.createRoutinePriv = createRoutinePriv;
	}

	public String getCreateTablespacePriv() {
		return this.createTablespacePriv;
	}

	public void setCreateTablespacePriv(String createTablespacePriv) {
		this.createTablespacePriv = createTablespacePriv;
	}

	public String getCreateTmpTablePriv() {
		return this.createTmpTablePriv;
	}

	public void setCreateTmpTablePriv(String createTmpTablePriv) {
		this.createTmpTablePriv = createTmpTablePriv;
	}

	public String getCreateUserPriv() {
		return this.createUserPriv;
	}

	public void setCreateUserPriv(String createUserPriv) {
		this.createUserPriv = createUserPriv;
	}

	public String getCreateViewPriv() {
		return this.createViewPriv;
	}

	public void setCreateViewPriv(String createViewPriv) {
		this.createViewPriv = createViewPriv;
	}

	public String getDefaultRole() {
		return this.defaultRole;
	}

	public void setDefaultRole(String defaultRole) {
		this.defaultRole = defaultRole;
	}

	public String getDeleteHistoryPriv() {
		return this.deleteHistoryPriv;
	}

	public void setDeleteHistoryPriv(String deleteHistoryPriv) {
		this.deleteHistoryPriv = deleteHistoryPriv;
	}

	public String getDeletePriv() {
		return this.deletePriv;
	}

	public void setDeletePriv(String deletePriv) {
		this.deletePriv = deletePriv;
	}

	public String getDropPriv() {
		return this.dropPriv;
	}

	public void setDropPriv(String dropPriv) {
		this.dropPriv = dropPriv;
	}

	public String getEventPriv() {
		return this.eventPriv;
	}

	public void setEventPriv(String eventPriv) {
		this.eventPriv = eventPriv;
	}

	public String getExecutePriv() {
		return this.executePriv;
	}

	public void setExecutePriv(String executePriv) {
		this.executePriv = executePriv;
	}

	public String getFilePriv() {
		return this.filePriv;
	}

	public void setFilePriv(String filePriv) {
		this.filePriv = filePriv;
	}

	public String getGrantPriv() {
		return this.grantPriv;
	}

	public void setGrantPriv(String grantPriv) {
		this.grantPriv = grantPriv;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getIndexPriv() {
		return this.indexPriv;
	}

	public void setIndexPriv(String indexPriv) {
		this.indexPriv = indexPriv;
	}

	public String getInsertPriv() {
		return this.insertPriv;
	}

	public void setInsertPriv(String insertPriv) {
		this.insertPriv = insertPriv;
	}

	public String getIsRole() {
		return this.isRole;
	}

	public void setIsRole(String isRole) {
		this.isRole = isRole;
	}

	public String getLockTablesPriv() {
		return this.lockTablesPriv;
	}

	public void setLockTablesPriv(String lockTablesPriv) {
		this.lockTablesPriv = lockTablesPriv;
	}

	public long getMaxConnections() {
		return this.maxConnections;
	}

	public void setMaxConnections(long maxConnections) {
		this.maxConnections = maxConnections;
	}

	public long getMaxQuestions() {
		return this.maxQuestions;
	}

	public void setMaxQuestions(long maxQuestions) {
		this.maxQuestions = maxQuestions;
	}

	public BigDecimal getMaxStatementTime() {
		return this.maxStatementTime;
	}

	public void setMaxStatementTime(BigDecimal maxStatementTime) {
		this.maxStatementTime = maxStatementTime;
	}

	public long getMaxUpdates() {
		return this.maxUpdates;
	}

	public void setMaxUpdates(long maxUpdates) {
		this.maxUpdates = maxUpdates;
	}

	public long getMaxUserConnections() {
		return this.maxUserConnections;
	}

	public void setMaxUserConnections(long maxUserConnections) {
		this.maxUserConnections = maxUserConnections;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordExpired() {
		return this.passwordExpired;
	}

	public void setPasswordExpired(String passwordExpired) {
		this.passwordExpired = passwordExpired;
	}

	public String getPlugin() {
		return this.plugin;
	}

	public void setPlugin(String plugin) {
		this.plugin = plugin;
	}

	public String getProcessPriv() {
		return this.processPriv;
	}

	public void setProcessPriv(String processPriv) {
		this.processPriv = processPriv;
	}

	public String getReferencesPriv() {
		return this.referencesPriv;
	}

	public void setReferencesPriv(String referencesPriv) {
		this.referencesPriv = referencesPriv;
	}

	public String getReloadPriv() {
		return this.reloadPriv;
	}

	public void setReloadPriv(String reloadPriv) {
		this.reloadPriv = reloadPriv;
	}

	public String getReplClientPriv() {
		return this.replClientPriv;
	}

	public void setReplClientPriv(String replClientPriv) {
		this.replClientPriv = replClientPriv;
	}

	public String getReplSlavePriv() {
		return this.replSlavePriv;
	}

	public void setReplSlavePriv(String replSlavePriv) {
		this.replSlavePriv = replSlavePriv;
	}

	public String getSelectPriv() {
		return this.selectPriv;
	}

	public void setSelectPriv(String selectPriv) {
		this.selectPriv = selectPriv;
	}

	public String getShowDbPriv() {
		return this.showDbPriv;
	}

	public void setShowDbPriv(String showDbPriv) {
		this.showDbPriv = showDbPriv;
	}

	public String getShowViewPriv() {
		return this.showViewPriv;
	}

	public void setShowViewPriv(String showViewPriv) {
		this.showViewPriv = showViewPriv;
	}

	public String getShutdownPriv() {
		return this.shutdownPriv;
	}

	public void setShutdownPriv(String shutdownPriv) {
		this.shutdownPriv = shutdownPriv;
	}

	public String getSslCipher() {
		return this.sslCipher;
	}

	public void setSslCipher(String sslCipher) {
		this.sslCipher = sslCipher;
	}

	public String getSslType() {
		return this.sslType;
	}

	public void setSslType(String sslType) {
		this.sslType = sslType;
	}

	public String getSuperPriv() {
		return this.superPriv;
	}

	public void setSuperPriv(String superPriv) {
		this.superPriv = superPriv;
	}

	public String getTriggerPriv() {
		return this.triggerPriv;
	}

	public void setTriggerPriv(String triggerPriv) {
		this.triggerPriv = triggerPriv;
	}

	public String getUpdatePriv() {
		return this.updatePriv;
	}

	public void setUpdatePriv(String updatePriv) {
		this.updatePriv = updatePriv;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getX509Issuer() {
		return this.x509Issuer;
	}

	public void setX509Issuer(String x509Issuer) {
		this.x509Issuer = x509Issuer;
	}

	public String getX509Subject() {
		return this.x509Subject;
	}

	public void setX509Subject(String x509Subject) {
		this.x509Subject = x509Subject;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return ((this.getAlterPriv() == castOther.getAlterPriv()) || (this.getAlterPriv() != null
				&& castOther.getAlterPriv() != null && this.getAlterPriv().equals(castOther.getAlterPriv())))
				&& ((this.getAlterRoutinePriv() == castOther.getAlterRoutinePriv())
						|| (this.getAlterRoutinePriv() != null && castOther.getAlterRoutinePriv() != null
								&& this.getAlterRoutinePriv().equals(castOther.getAlterRoutinePriv())))
				&& ((this.getAuthenticationString() == castOther.getAuthenticationString())
						|| (this.getAuthenticationString() != null && castOther.getAuthenticationString() != null
								&& this.getAuthenticationString().equals(castOther.getAuthenticationString())))
				&& ((this.getCreatePriv() == castOther.getCreatePriv()) || (this.getCreatePriv() != null
						&& castOther.getCreatePriv() != null && this.getCreatePriv().equals(castOther.getCreatePriv())))
				&& ((this.getCreateRoutinePriv() == castOther.getCreateRoutinePriv())
						|| (this.getCreateRoutinePriv() != null && castOther.getCreateRoutinePriv() != null
								&& this.getCreateRoutinePriv().equals(castOther.getCreateRoutinePriv())))
				&& ((this.getCreateTablespacePriv() == castOther.getCreateTablespacePriv())
						|| (this.getCreateTablespacePriv() != null && castOther.getCreateTablespacePriv() != null
								&& this.getCreateTablespacePriv().equals(castOther.getCreateTablespacePriv())))
				&& ((this.getCreateTmpTablePriv() == castOther.getCreateTmpTablePriv())
						|| (this.getCreateTmpTablePriv() != null && castOther.getCreateTmpTablePriv() != null
								&& this.getCreateTmpTablePriv().equals(castOther.getCreateTmpTablePriv())))
				&& ((this.getCreateUserPriv() == castOther.getCreateUserPriv())
						|| (this.getCreateUserPriv() != null && castOther.getCreateUserPriv() != null
								&& this.getCreateUserPriv().equals(castOther.getCreateUserPriv())))
				&& ((this.getCreateViewPriv() == castOther.getCreateViewPriv())
						|| (this.getCreateViewPriv() != null && castOther.getCreateViewPriv() != null
								&& this.getCreateViewPriv().equals(castOther.getCreateViewPriv())))
				&& ((this.getDefaultRole() == castOther.getDefaultRole())
						|| (this.getDefaultRole() != null && castOther.getDefaultRole() != null
								&& this.getDefaultRole().equals(castOther.getDefaultRole())))
				&& ((this.getDeleteHistoryPriv() == castOther.getDeleteHistoryPriv())
						|| (this.getDeleteHistoryPriv() != null && castOther.getDeleteHistoryPriv() != null
								&& this.getDeleteHistoryPriv().equals(castOther.getDeleteHistoryPriv())))
				&& ((this.getDeletePriv() == castOther.getDeletePriv()) || (this.getDeletePriv() != null
						&& castOther.getDeletePriv() != null && this.getDeletePriv().equals(castOther.getDeletePriv())))
				&& ((this.getDropPriv() == castOther.getDropPriv()) || (this.getDropPriv() != null
						&& castOther.getDropPriv() != null && this.getDropPriv().equals(castOther.getDropPriv())))
				&& ((this.getEventPriv() == castOther.getEventPriv()) || (this.getEventPriv() != null
						&& castOther.getEventPriv() != null && this.getEventPriv().equals(castOther.getEventPriv())))
				&& ((this.getExecutePriv() == castOther.getExecutePriv())
						|| (this.getExecutePriv() != null && castOther.getExecutePriv() != null
								&& this.getExecutePriv().equals(castOther.getExecutePriv())))
				&& ((this.getFilePriv() == castOther.getFilePriv()) || (this.getFilePriv() != null
						&& castOther.getFilePriv() != null && this.getFilePriv().equals(castOther.getFilePriv())))
				&& ((this.getGrantPriv() == castOther.getGrantPriv()) || (this.getGrantPriv() != null
						&& castOther.getGrantPriv() != null && this.getGrantPriv().equals(castOther.getGrantPriv())))
				&& ((this.getHost() == castOther.getHost()) || (this.getHost() != null && castOther.getHost() != null
						&& this.getHost().equals(castOther.getHost())))
				&& ((this.getIndexPriv() == castOther.getIndexPriv()) || (this.getIndexPriv() != null
						&& castOther.getIndexPriv() != null && this.getIndexPriv().equals(castOther.getIndexPriv())))
				&& ((this.getInsertPriv() == castOther.getInsertPriv()) || (this.getInsertPriv() != null
						&& castOther.getInsertPriv() != null && this.getInsertPriv().equals(castOther.getInsertPriv())))
				&& ((this.getIsRole() == castOther.getIsRole()) || (this.getIsRole() != null
						&& castOther.getIsRole() != null && this.getIsRole().equals(castOther.getIsRole())))
				&& ((this.getLockTablesPriv() == castOther.getLockTablesPriv())
						|| (this.getLockTablesPriv() != null && castOther.getLockTablesPriv() != null
								&& this.getLockTablesPriv().equals(castOther.getLockTablesPriv())))
				&& (this.getMaxConnections() == castOther.getMaxConnections())
				&& (this.getMaxQuestions() == castOther.getMaxQuestions())
				&& ((this.getMaxStatementTime() == castOther.getMaxStatementTime())
						|| (this.getMaxStatementTime() != null && castOther.getMaxStatementTime() != null
								&& this.getMaxStatementTime().equals(castOther.getMaxStatementTime())))
				&& (this.getMaxUpdates() == castOther.getMaxUpdates())
				&& (this.getMaxUserConnections() == castOther.getMaxUserConnections())
				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())))
				&& ((this.getPasswordExpired() == castOther.getPasswordExpired())
						|| (this.getPasswordExpired() != null && castOther.getPasswordExpired() != null
								&& this.getPasswordExpired().equals(castOther.getPasswordExpired())))
				&& ((this.getPlugin() == castOther.getPlugin()) || (this.getPlugin() != null
						&& castOther.getPlugin() != null && this.getPlugin().equals(castOther.getPlugin())))
				&& ((this.getProcessPriv() == castOther.getProcessPriv())
						|| (this.getProcessPriv() != null && castOther.getProcessPriv() != null
								&& this.getProcessPriv().equals(castOther.getProcessPriv())))
				&& ((this.getReferencesPriv() == castOther.getReferencesPriv())
						|| (this.getReferencesPriv() != null && castOther.getReferencesPriv() != null
								&& this.getReferencesPriv().equals(castOther.getReferencesPriv())))
				&& ((this.getReloadPriv() == castOther.getReloadPriv()) || (this.getReloadPriv() != null
						&& castOther.getReloadPriv() != null && this.getReloadPriv().equals(castOther.getReloadPriv())))
				&& ((this.getReplClientPriv() == castOther.getReplClientPriv())
						|| (this.getReplClientPriv() != null && castOther.getReplClientPriv() != null
								&& this.getReplClientPriv().equals(castOther.getReplClientPriv())))
				&& ((this.getReplSlavePriv() == castOther.getReplSlavePriv())
						|| (this.getReplSlavePriv() != null && castOther.getReplSlavePriv() != null
								&& this.getReplSlavePriv().equals(castOther.getReplSlavePriv())))
				&& ((this.getSelectPriv() == castOther.getSelectPriv()) || (this.getSelectPriv() != null
						&& castOther.getSelectPriv() != null && this.getSelectPriv().equals(castOther.getSelectPriv())))
				&& ((this.getShowDbPriv() == castOther.getShowDbPriv()) || (this.getShowDbPriv() != null
						&& castOther.getShowDbPriv() != null && this.getShowDbPriv().equals(castOther.getShowDbPriv())))
				&& ((this.getShowViewPriv() == castOther.getShowViewPriv())
						|| (this.getShowViewPriv() != null && castOther.getShowViewPriv() != null
								&& this.getShowViewPriv().equals(castOther.getShowViewPriv())))
				&& ((this.getShutdownPriv() == castOther.getShutdownPriv())
						|| (this.getShutdownPriv() != null && castOther.getShutdownPriv() != null
								&& this.getShutdownPriv().equals(castOther.getShutdownPriv())))
				&& ((this.getSslCipher() == castOther.getSslCipher()) || (this.getSslCipher() != null
						&& castOther.getSslCipher() != null && this.getSslCipher().equals(castOther.getSslCipher())))
				&& ((this.getSslType() == castOther.getSslType()) || (this.getSslType() != null
						&& castOther.getSslType() != null && this.getSslType().equals(castOther.getSslType())))
				&& ((this.getSuperPriv() == castOther.getSuperPriv()) || (this.getSuperPriv() != null
						&& castOther.getSuperPriv() != null && this.getSuperPriv().equals(castOther.getSuperPriv())))
				&& ((this.getTriggerPriv() == castOther.getTriggerPriv())
						|| (this.getTriggerPriv() != null && castOther.getTriggerPriv() != null
								&& this.getTriggerPriv().equals(castOther.getTriggerPriv())))
				&& ((this.getUpdatePriv() == castOther.getUpdatePriv()) || (this.getUpdatePriv() != null
						&& castOther.getUpdatePriv() != null && this.getUpdatePriv().equals(castOther.getUpdatePriv())))
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
						&& this.getUser().equals(castOther.getUser())))
				&& ((this.getX509Issuer() == castOther.getX509Issuer()) || (this.getX509Issuer() != null
						&& castOther.getX509Issuer() != null && this.getX509Issuer().equals(castOther.getX509Issuer())))
				&& ((this.getX509Subject() == castOther.getX509Subject())
						|| (this.getX509Subject() != null && castOther.getX509Subject() != null
								&& this.getX509Subject().equals(castOther.getX509Subject())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAlterPriv() == null ? 0 : this.getAlterPriv().hashCode());
		result = 37 * result + (getAlterRoutinePriv() == null ? 0 : this.getAlterRoutinePriv().hashCode());
		result = 37 * result + (getAuthenticationString() == null ? 0 : this.getAuthenticationString().hashCode());
		result = 37 * result + (getCreatePriv() == null ? 0 : this.getCreatePriv().hashCode());
		result = 37 * result + (getCreateRoutinePriv() == null ? 0 : this.getCreateRoutinePriv().hashCode());
		result = 37 * result + (getCreateTablespacePriv() == null ? 0 : this.getCreateTablespacePriv().hashCode());
		result = 37 * result + (getCreateTmpTablePriv() == null ? 0 : this.getCreateTmpTablePriv().hashCode());
		result = 37 * result + (getCreateUserPriv() == null ? 0 : this.getCreateUserPriv().hashCode());
		result = 37 * result + (getCreateViewPriv() == null ? 0 : this.getCreateViewPriv().hashCode());
		result = 37 * result + (getDefaultRole() == null ? 0 : this.getDefaultRole().hashCode());
		result = 37 * result + (getDeleteHistoryPriv() == null ? 0 : this.getDeleteHistoryPriv().hashCode());
		result = 37 * result + (getDeletePriv() == null ? 0 : this.getDeletePriv().hashCode());
		result = 37 * result + (getDropPriv() == null ? 0 : this.getDropPriv().hashCode());
		result = 37 * result + (getEventPriv() == null ? 0 : this.getEventPriv().hashCode());
		result = 37 * result + (getExecutePriv() == null ? 0 : this.getExecutePriv().hashCode());
		result = 37 * result + (getFilePriv() == null ? 0 : this.getFilePriv().hashCode());
		result = 37 * result + (getGrantPriv() == null ? 0 : this.getGrantPriv().hashCode());
		result = 37 * result + (getHost() == null ? 0 : this.getHost().hashCode());
		result = 37 * result + (getIndexPriv() == null ? 0 : this.getIndexPriv().hashCode());
		result = 37 * result + (getInsertPriv() == null ? 0 : this.getInsertPriv().hashCode());
		result = 37 * result + (getIsRole() == null ? 0 : this.getIsRole().hashCode());
		result = 37 * result + (getLockTablesPriv() == null ? 0 : this.getLockTablesPriv().hashCode());
		result = 37 * result + (int) this.getMaxConnections();
		result = 37 * result + (int) this.getMaxQuestions();
		result = 37 * result + (getMaxStatementTime() == null ? 0 : this.getMaxStatementTime().hashCode());
		result = 37 * result + (int) this.getMaxUpdates();
		result = 37 * result + (int) this.getMaxUserConnections();
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result + (getPasswordExpired() == null ? 0 : this.getPasswordExpired().hashCode());
		result = 37 * result + (getPlugin() == null ? 0 : this.getPlugin().hashCode());
		result = 37 * result + (getProcessPriv() == null ? 0 : this.getProcessPriv().hashCode());
		result = 37 * result + (getReferencesPriv() == null ? 0 : this.getReferencesPriv().hashCode());
		result = 37 * result + (getReloadPriv() == null ? 0 : this.getReloadPriv().hashCode());
		result = 37 * result + (getReplClientPriv() == null ? 0 : this.getReplClientPriv().hashCode());
		result = 37 * result + (getReplSlavePriv() == null ? 0 : this.getReplSlavePriv().hashCode());
		result = 37 * result + (getSelectPriv() == null ? 0 : this.getSelectPriv().hashCode());
		result = 37 * result + (getShowDbPriv() == null ? 0 : this.getShowDbPriv().hashCode());
		result = 37 * result + (getShowViewPriv() == null ? 0 : this.getShowViewPriv().hashCode());
		result = 37 * result + (getShutdownPriv() == null ? 0 : this.getShutdownPriv().hashCode());
		result = 37 * result + (getSslCipher() == null ? 0 : this.getSslCipher().hashCode());
		result = 37 * result + (getSslType() == null ? 0 : this.getSslType().hashCode());
		result = 37 * result + (getSuperPriv() == null ? 0 : this.getSuperPriv().hashCode());
		result = 37 * result + (getTriggerPriv() == null ? 0 : this.getTriggerPriv().hashCode());
		result = 37 * result + (getUpdatePriv() == null ? 0 : this.getUpdatePriv().hashCode());
		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		result = 37 * result + (getX509Issuer() == null ? 0 : this.getX509Issuer().hashCode());
		result = 37 * result + (getX509Subject() == null ? 0 : this.getX509Subject().hashCode());
		return result;
	}

}
